GET http://localhost:3000/peliculas HTTP/1.1
###
GET http://localhost:3000/peliculas/3 HTTP/1.1

###
POST http://localhost:3000/peliculas HTTP/1.1
Content-Type: application/json

{
    "titulo": "Inception",
    "director": "Christopher Nolan",
    "year": 2010,
    "pais": "USA"
}

###
PUT http://localhost:3000/peliculas/4 HTTP/1.1
Content-Type: application/json

{
    "titulo": "Ice Age",
    "director": "Chris Wedge",
    "year": 2010,
    "pais": "USA"
}

###
DELETE http://localhost:3000/peliculas/4 HTTP/1.1
